[workspace]
resolver = "3"
members = ["xodus", "xodus-cli"]

[workspace.dependencies]
chrono = "0.4.42"
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
